services:
  frontend:
    restart: always
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app:rw
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    restart: always
    build: ./api
    ports:
      - '5050:5050'
    volumes:
      - ./api:/app
  mongo:
    image: "mongo:4.4.16"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: nothing_10
    volumes:
      - mongodb_data:/data/db
  mongo-express:
    image: mongo-express:1.0
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: nothing_10
    depends_on:
      - mongo
volumes:
  mongodb_data: